### ISSUE TITLE
Ability to ask a persistent capture control permission

### ISSUE THREAD

**Issue by GirlLily** [emanuele-f/PCAPdroid#138] opened 2021-10-30 13:24 UTC
Hey, is it a way to implement this? I just want it to request permission one time when I start to capture. And no matter how many apps will be captured later.

**Comment by emanuele-f** [comment] 2021-10-31 08:48
It is requested to add the ability to grant an app a persistent capture control permission (when using the [app API](https://github.com/emanuele-f/PCAPdroid/blob/master/docs/app_api.md)), so that the permission popup won't be shown every time the capture is started/stopped. The user should be able to review the granted permissions and revoke them at any time.

**Comment by GirlLily** [comment] 2021-10-31 09:09
But it did show every time.

Emanuele Faranda ***@***.***>于2021年10月31日 周日08:48写道：

**Comment by emanuele-f** [comment] 2021-10-31 09:11
Yeah, that is the current behavior. This FR is to grant a "persistent" permission, so that it won't be shown every time anymore

**Comment by GirlLily** [comment] 2021-10-31 09:22
So how to fix it in my app?

Emanuele Faranda ***@***.***>于2021年10月31日 周日09:11写道：

**Comment by emanuele-f** [comment] 2021-10-31 09:24
This needs to be implemented in PCAPdroid first

**Comment by GirlLily** [comment] 2021-10-31 09:24
Oh, I see

Emanuele Faranda ***@***.***>于2021年10月31日 周日09:24写道：

**Comment by GirlLily** [comment] 2021-11-01 09:44
May I know when it will be fixed😂

**Comment by emanuele-f** [comment] 2021-11-01 19:47
If you want this kind of guarantee you should consider paying me!

**Comment by GirlLily** [comment] 2021-11-01 20:29
How much I need to pay?

**Comment by emanuele-f** [comment] 2021-11-02 08:34
This is not the right place to discuss this, please contact me via email

**Comment by emanuele-f** [comment] 2021-11-04 18:16
You can now select "Forever" to avoid showing subsequent popups.

![2021-11-04_19-08](https://user-images.githubusercontent.com/5488003/140396377-6a66e5a4-fa34-4fa3-bb2d-c4cc6dcea0b0.png)

Control permissions rules can be reviewed/deleted from the settings activity.

You can test this new feature in the [latest debug apk](https://github.com/emanuele-f/PCAPdroid/suites/4259427439/artifacts/110633848).

**Comment by GirlLily** [comment] 2021-11-04 18:17
Thanks, I'll check it out.

**Comment by emanuele-f** [comment] 2021-11-22 18:39
No feedback received so I assume that this works as intended. It is now also possible to query the capture status as explained in the [docs](https://github.com/emanuele-f/PCAPdroid/blob/dev/docs/app_api.md#query-the-capture-status).

**Comment by GirlLily** [comment] 2021-11-22 18:41
Hi, I’m sorry I haven’t checked it, coz I was busy with machine learning
stuff recently.

**Comment by emanuele-f** [comment] 2021-11-22 18:59
Don't worry, if you find any issues please report them here and I'll reopen the issue. Closing for now. The next release will be available soon.

**Closed by emanuele-f** 2021-11-22 18:59 UTC
Labels: enhancement

**Comment by GirlLily** [comment] 2021-11-22 19:01
Awesome, thanks!

**Comment by MercuialC** [comment] 2024-06-18 03:23
> From the permission dialog the user can choose to permanently grant or deny the capture permission to an app. The permanently granted/denied permissions can be edited from the entry in the PCAPdroid settings.Control Permissions

I am using the adb command to start capturing in version 1.7.2. How can I set permissions or authorize subsequent openings without the pop-up window? I haven't found the relevant entry. Can you tell me how to do it? Thank you very much for your great work.

**Comment by emanuele-f** [comment] 2024-06-18 08:20
Hi @MercuialC, it's not currently possible to authorize this permanently for adb, because it does not provide the package name.

As a workaround you can build a simple cli executable for android, which calls startActivityForResult/ActivityResultLauncher. Check out docs/app_api.md, "User consent" section
