### ISSUE TITLE
Already connected VPN - show error when attempting PcapDroid start

### ISSUE THREAD

**Issue by fusionneur** [emanuele-f/PCAPdroid#13] opened 2021-01-18 15:08 UTC
Nothing being captured.

Android 10
Latest version as of today in fdroid

**Comment by emanuele-f** [comment] 2021-01-18 22:22
As far as I know, PCAPdroid is not on fdroid. This is the latest version: https://github.com/emanuele-f/PCAPdroid/releases/tag/v1.2.9, please ensure that you are using this. Do you see anything in the connections tab? Are you using an [app filter](https://emanuele-f.github.io/PCAPdroid/quick_start#13-app-filter)? Which [dump mode](https://emanuele-f.github.io/PCAPdroid/dump_modes)?

**Comment by fusionneur** [comment] 2021-01-18 22:56
Sorry I use a different repo inside aurora droid. It's from izzyondroid.

I am on 1.2.9.12

After pressing start, nothing really happens. I see a ready on status page and on connections tab i see "no connections".

Dump mode: HTTP Server

I have a more complex environment which involves: afwall + netguard + xprivacylua but i allowed all that it is to be allowed with no help.

**Comment by fusionneur** [comment] 2021-01-18 22:57
More details.
I am on android 10.
I remember trying the app about two more times in the past months on different versions, but was not working for me.

**Comment by emanuele-f** [comment] 2021-01-19 09:25
After pressing "Start", the app will start the VpnService, the button will show "Stop" and the "Ready" text will be replaced with the number of bytes captured. In your case it seems like the VpnService is not even started. I'm not familiar with xprivacylua but I understand that it seats between apps and OS, it may be the cause of the issue. Moreover, in android you can only run one VpnService at once, so you cannot run PcapDroid while netguard is running.

**Comment by fusionneur** [comment] 2021-01-19 18:21
Ah in this case I suppose that's because netguard already has a vpn set up. In this case I suppose an error message should be presented.

**Comment by emanuele-f** [comment] 2021-01-19 23:22
I've tried running PcapDroid while Netguard is running, in such a case the Netguard VpnService is stopped, so it does not reproduce your issue. Can you provide a logcat log of PCAPdroid while experiencing the issue?

**Comment by fusionneur** [comment] 2021-01-20 17:25
Did you try on Android 10 ? In my case, netguard does not stop when starting PcapDroid.  In any case, my suggestion is that PcapDroid shouldn't stop an already connected vpn or else data could leak for those who use public vpn or firewall as vpn.

Until Android offers the possibility of vpn chaining, I can only see one way to handle this situation:
1. PcapDroid should identifyr connected VPN and print a banner saying that it will not work until currently connected VPN stops
2. throw an error when attempting to start PcapDroid if already connected to VPN upon . Alternatively, the start button could be grayed out if VPN already connected

**Comment by emanuele-f** [comment] 2021-01-21 21:11
With e1a6436489a395fe3bdf19f901e74ac54991dc36 now a user confirmation is asked before dropping the running VPNService. However this still does not fix your issue. I've tested it on Android 11 and it terminates the old VPNService connection. Android logs and screenshots are needed to understand what's going wrong. I still suspect xprivacylua or similar software is the cause.

**Comment by emanuele-f** [comment] 2021-02-07 17:20
@fusionneur do you have any news/logs to inspect?

**Comment by fusionneur** [comment] 2021-02-08 11:28
Sorry.. I cannot provide any logs as I have vpn enabled all the time. Unfortunatelly I cannot make use of this app..

**Comment by emanuele-f** [comment] 2021-02-09 11:20
Ok, closing for now

**Closed by emanuele-f** 2021-02-09 11:20 UTC
