### ISSUE TITLE
Capture multi apps traffic

### ISSUE THREAD

**Issue by 67113513** [emanuele-f/PCAPdroid#315] opened 2023-04-27 14:28 UTC
Does it possible add two or more app names on capture list and then start capture? It will be convenience for people who wants many apps' traffic but doesn't care the sequence.

**Comment by emanuele-f** [comment] 2023-04-28 04:43
Hi, closing as a duplicate of https://github.com/emanuele-f/PCAPdroid/issues/146. This require some changes in the ui and backend but is feasible.

**Closed by emanuele-f** 2023-04-28 04:43 UTC
