### ISSUE TITLE
Fix paid features navigation via remote control

### ISSUE THREAD

**Issue by bbigam** [emanuele-f/PCAPdroid#295] opened 2023-02-03 22:07 UTC
I'm using PCAPdroid 1.6.0 on a RockTek G2, a recent Android TV 11 device. I paid for the no root firewall specifically to use it on this device. But it doesn't show up in the sidebar. In the paid features section, it's listed with the options Learn More and Buy, but they aren't functional. I can scroll the list but not select anything. If I choose the block option from the context menu of a connection, I get sent to the same nonfunctional paid features page.
I have the exact same problem on my Chromecast with Google TV.

I made the purchase from my phone using the same Google account that I'm signed into on the G2 and Chromecast. The firewall works on my phone, but that's not what I got it for.

I tried clearing app cache and data. I tried uninstalling and reinstalling the app. Restarted the G2. Nothing made any difference.

Am I missing something, or is this a bug, or are paid features not available in Android TV despite being listed as options?

**Comment by emanuele-f** [comment] 2023-02-04 11:52
This seems like a bug, I'm checking this asap

**Comment by emanuele-f** [comment] 2023-02-04 12:13
Cannot reproduce this with Google tv, the features correctly appear in the left drawer and the "buy" button works. It seems an issue in the communication between your tv device(s) and Google Play. Please report the following information:

1. In the left drawer, go into About and select the info icon in the top bar. It will display the build info. Please attach here
2. In the left drawer, go into Log and copy attach here the app log

**Comment by bbigam** [comment] 2023-02-04 14:11
Hello, thanks for the quick response. Maybe my bug report was a little hasty - I'm happy to note that the firewall appeared within a couple of hours of my bug report, and it does work correctly. Maybe Google Play was a little slow at sending on the purchase info.
Still, the Paid Features page doesn't work.
[pcap.txt](https://github.com/emanuele-f/PCAPdroid/files/10608812/pcap.txt)

**Comment by bbigam** [comment] 2023-02-04 14:17
Some more information: On the firewall - status page, I can't navigate down to connections blocked and select it. Similarly, in the build info page I couldn't navigate to copy. But I could on the log page.

_However_ - I tried attaching a touchpad and I was able to access all of these features, including the buy button on the paid features page, with the cursor using the touchpad. But there was no possible way to get to them with the remote control. Chromecast has the same trouble.

So, there's no problem using paid features on Android TV after all. But there is a problem navigating parts of some screens using a remote control.

**Comment by emanuele-f** [comment] 2023-02-04 16:51
Thanks for the clarification. I used the Android emulator to test this (no remote controls), but I will probably need to test and fix this on a physical device. This will be part of 1.6.1, which you can expect to be release within next week.

**Comment by bbigam** [comment] 2023-02-04 17:10
Thanks for the quick response. While we're on the topic of remote navigation in Android TV, in addition to 1) the paid features page, 2) the copy button on the build info, and 3) the connections blocked section on the firewall, I'd also like to request an option to reverse the sort order on connections pages (ascending/descending). It's tedious to scroll to the bottom of hundreds of connections using a remote to see the newest ones. It would be nice to have the option to sort the most recent connections to the top of the list.

I'll certainly try out 1.6.1 when it comes and let you know what works.

**Closed** 2023-02-09 09:48 UTC
Labels: bug

**Comment by emanuele-f** [comment] 2023-02-09 09:55
Thanks for your report, Android tv navigation is now fixed.
Regarding the jump to button, you should already be able to reach it by pressing the right dpad button after selecting any item in the connections list. Once pressed, it autoscrolls on every new connection.
With some minor exceptions, item highlighting corresponds to focus. So if item is not highlighted, there is no focus and you cannot click it. The problem with supporting Android tv is mostly to figure out how to indicate the focus correctly. For the most part, this is a trial and error task.

**Comment by bbigam** [comment] 2023-02-09 11:46
Thanks, will test once I get the update!

**Comment by emanuele-f** [comment] 2023-02-10 07:48
The new version has been released, check it out.

**Comment by bbigam** [comment] 2023-02-10 12:59
Most of the problems have been fixed, in my testing. However, two remain:
I still can't navigate the lower half of the Firewall Status page. I can
scroll down, but not select anything.
On the connections page for an individual app, I can't navigate to the down
button. This does work correctly on the general connections page.

**Comment by bbigam** [comment] 2023-02-10 13:01
I forgot to clarify that this is on a Chromecast using the standard remote
control.

**Comment by emanuele-f** [comment] 2023-02-10 13:56
Thanks for your feedback. I've opened a new issue for the connections. Regarding the firewall status, navigation, the current behavior is expected, no selection is allowed.

**Comment by bbigam** [comment] 2023-02-10 14:28
Got it, thanks.
