### ISSUE TITLE
Whitelist actions

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#381] opened 2023-12-17 16:34 UTC
Why are there Host and IP items available for adding to Blocklist but there no similar items for Whitelist? ;)

**Comment by emanuele-f** [comment] 2023-12-17 18:04
Mainly ease of implementation, due to the limited use case

**Comment by anpic** [comment] 2023-12-17 18:35
> Mainly ease of implementation, due to the limited use case

This is in the same piggy bank as https://github.com/emanuele-f/PCAPdroid/issues/374  :)
I really miss it.
I have to communicate with other so-called developers who don't understand how to make the firewall itself ;)

**Comment by anpic** [comment] 2023-12-17 19:02
And so I missed the same one issue https://github.com/emanuele-f/PCAPdroid/issues/302

**Comment by emanuele-f** [comment] 2023-12-18 18:07
Right, this is a duplicate of #302

**Closed by emanuele-f** 2023-12-18 18:07 UTC
